server:
  port: 8081

spring:
  application:
    name: ACCOUNT

  datasource:
    url: jdbc:h2:mem:accountsdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
