server:
  port: 8085

spring:
  application:
    name: ORDER

  datasource:
    url: jdbc:h2:mem:ordersdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
management:
  server:
    port: 7085
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://store-service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true