networks:
  store-network:
    driver: bridge
    ipam:
      driver: default

services:
  store-service-discovery:
    image: store-service-discovery:1.0-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - store-network

  account:
    depends_on:
      - rabbitmq
      - store-service-discovery
    image: account:1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
        - store-network

  product:
    depends_on:
      - rabbitmq
      - store-service-discovery
    image: product:1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - store-network

  store-gateway:
    depends_on:
      - rabbitmq
      - store-service-discovery
    image: store-gateway:1.0-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - store-network

  orders-management:
    depends_on:
      - rabbitmq
      - store-service-discovery
    image: orders-management:1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - store-network

  orders-consumer:
    depends_on:
      - rabbitmq
      - store-service-discovery
    image: orders-consumer:1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - store-network

  rabbitmq:
    image: rabbitmq:4-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq-config-volume:/etc/rabbitmq/
    networks:
      - store-network

volumes:
  rabbitmq-config-volume: