server:
  port: 8082

spring:
  application:
    name: PRODUCT

  datasource:
    url: jdbc:h2:mem:productsdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

management:
  server:
    port: 7082
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always